// <auto-generated />
namespace School.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SecondInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "202003301421537_SecondInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
